name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Docker Image
      run: sudo docker pull rachit98/python-qr-code:latest
    - name: Delete Old Docker Container
      run: sudo docker rm -f python-qr-code || true
    - name: Run Docker Container
      run: sudo docker run -d -p 5000:5000 --name python-qr-code rachit98/python-qr-code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker buildx build --platform linux/amd64,linux/arm64 -t rachit98/python-qr-code:latest -f Dockerfile --push .
