name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: docker pull rachit98/python-qr-code:latest


    - name: Run Docker container on EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PASSWORD }} ubuntu@${{ secrets.EC2_INSTANCE_IP }} "docker pull rachit98/python-qr-code:latest && docker run -d -p 5000:5000 rachit98/python-qr-code:latest"
